### ISSUE TITLE
Crash when socket is not available

### ISSUE THREAD

**Issue by pierre-vigier** [atancasis/Dancer2-Logger-Fluent#1]
If the fluent daemon is not responding, the logger is crashing with internal server error.

**Comment by atancasis** [comment]
Hi @pierre-vigier, thanks for pointing out this issue!

I've implemented a fix and/or feature to queue messages for deferred flushing until a connection to the `fluentd` agent can be established.

This is implemented in version [`0.03`](https://github.com/atancasis/Dancer2-Logger-Fluent/releases/tag/0.03), in commit [`42dc6c33`](https://github.com/atancasis/Dancer2-Logger-Fluent/commit/42d6c3392c6e30d1d9aa9ec0e7ad2a179c1ab669).

Thanks again!
